apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        # image: mirdsmulya/hello-world:v0.0.1-java
        image: mirdsmulya/hello-world:v0.0.1
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
            # memory: 500Mi
          limits: 
            cpu: 100m
            memory: 100Mi
            # memory: 500Mi




